#! /bin/sh

set -x

# Gleaned from fp-compiler postinst

CFG_PATH='/etc/fpc.cfg'
PKG_CFG_PATH="/etc/fpc-2.6.4.cfg"
LIB_DIR="/usr/lib/fpc"
MAN_DIR="/usr/share/man/man1"

mkdir -p ${DESTDIR}/etc

/usr/bin/fpcmkcfg-2.6.4 -0 -d "basepath=${LIB_DIR}/\$fpcversion" -o "${DESTDIR}/${PKG_CFG_PATH}"
echo '-Fl/usr/lib/$fpctarget0*' >> ${DESTDIR}/${PKG_CFG_PATH}
cat >> ${DESTDIR}/${PKG_CFG_PATH} <<EOF
# Third party units should be installe in a, multi-arch compatible location.
# Units should be installed in /usr/lib/\$fpctarget-gnu/fp-units-2.6.2/\$pkg/.
# Ech fp-units package should install a configuration file called \$pkg.cfg in
#CFGDIR /etc/fpc-\$fpcversion.cfg.d/\$fpctarget
EOF

mkdir -p ${DESTDIR}/usr/bin ${DESTDIR}/${MAN_DIR}

ln -s /usr/bin/fpc-2.6.4 ${DESTDIR}/usr/bin/fpc
ln -s ${LIB_DIR}/2.6.4/ppcx64 ${DESTDIR}/usr/bin/ppcx64
ln -s /usr/bin/fpc-depends-2.6.4 ${DESTDIR}/usr/bin/fpc-depends
ln -s /usr/bin/fpcres-2.6.4 ${DESTDIR}/usr/bin/fpcres
ln -s ${MAN_DIR}/ppcx64-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ppcx64.1.gz
ln -s ${MAN_DIR}/fpc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpc.1.gz
ln -s ${MAN_DIR}/fpc-depends-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpc-depends.1.gz
ln -s ${PKG_CFG_PATH} ${CFG_PATH}

# Gleaned from fp-utils postinst

FPCDIR=/usr/lib/fpc

mkdir -p ${DESTDIR}/${FPCDIR} ${DESTDIR}/usr/share/man/man5

ln -s ${FPCDIR}/2.6.4 ${DESTDIR}/${FPCDIR}/default
ln -s ${FPCDIR}/2.6.4/lexyacc ${DESTDIR}/${FPCDIR}/lexyacc
ln -s /usr/bin/chmcmd-2.6.4 ${DESTDIR}/usr/bin/chmcmd
ln -s /usr/bin/chmls-2.6.4 ${DESTDIR}/usr/bin/chmls
ln -s /usr/bin/ifpc-2.6.4 ${DESTDIR}/usr/bin/ifpc
ln -s /usr/bin/fppkg-2.6.4 ${DESTDIR}/usr/bin/fppkg
ln -s /usr/bin/ifpc-2.6.4 ${DESTDIR}/usr/bin/instantfpc
ln -s /usr/bin/ppufiles-2.6.4 ${DESTDIR}/usr/bin/ppufiles
ln -s /usr/bin/ppudump-2.6.4 ${DESTDIR}/usr/bin/ppudump
ln -s /usr/bin/ppumove-2.6.4 ${DESTDIR}/usr/bin/ppumove
ln -s /usr/bin/ppdep-2.6.4 ${DESTDIR}/usr/bin/ppdep
ln -s /usr/bin/ptop-2.6.4 ${DESTDIR}/usr/bin/ptop
ln -s /usr/bin/rstconv-2.6.4 ${DESTDIR}/usr/bin/rstconv
ln -s /usr/bin/data2inc-2.6.4 ${DESTDIR}/usr/bin/data2inc
ln -s /usr/bin/bin2obj-2.6.4 ${DESTDIR}/usr/bin/bin2obj
ln -s /usr/bin/delp-2.6.4 ${DESTDIR}/usr/bin/delp
ln -s /usr/bin/plex-2.6.4 ${DESTDIR}/usr/bin/plex
ln -s /usr/bin/pyacc-2.6.4 ${DESTDIR}/usr/bin/pyacc
ln -s /usr/bin/h2pas-2.6.4 ${DESTDIR}/usr/bin/h2pas
ln -s /usr/bin/h2paspp-2.6.4 ${DESTDIR}/usr/bin/h2paspp
ln -s /usr/bin/postw32-2.6.4 ${DESTDIR}/usr/bin/postw32
ln -s /usr/bin/fpclasschart-2.6.4 ${DESTDIR}/usr/bin/fpclasschart
ln -s /usr/bin/fpcmake-2.6.4 ${DESTDIR}/usr/bin/fpcmake
ln -s /usr/bin/fpcsubst-2.6.4 ${DESTDIR}/usr/bin/fpcsubst
ln -s /usr/bin/fprcp-2.6.4 ${DESTDIR}/usr/bin/fprcp
ln -s /usr/bin/fpdoc-2.6.4 ${DESTDIR}/usr/bin/fpdoc
ln -s /usr/bin/makeskel-2.6.4 ${DESTDIR}/usr/bin/makeskel
ln -s /usr/bin/relpath-2.6.4 ${DESTDIR}/usr/bin/relpath
ln -s /usr/bin/rmcvsdir-2.6.4 ${DESTDIR}/usr/bin/rmcvsdir
ln -s /usr/bin/unitdiff-2.6.4 ${DESTDIR}/usr/bin/unitdiff
ln -s ${MAN_DIR}/chmcmd-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/chmcmd.1.gz
ln -s ${MAN_DIR}/chmls-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/chmls.1.gz
ln -s ${MAN_DIR}/ifpc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ifpc.1.gz
ln -s ${MAN_DIR}/fppkg-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fppkg.1.gz
ln -s ${MAN_DIR}/ifpc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/instantfpc.1.gz
ln -s ${MAN_DIR}/bin2obj-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/bin2obj.1.gz
ln -s ${MAN_DIR}/data2inc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/data2inc.1.gz
ln -s ${MAN_DIR}/fprcp-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fprcp.1.gz
ln -s ${MAN_DIR}/h2paspp-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/h2paspp.1.gz
ln -s ${MAN_DIR}/makeskel-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/makeskel.1.gz
ln -s ${MAN_DIR}/postw32-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/postw32.1.gz
ln -s ${MAN_DIR}/relpath-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/relpath.1.gz
ln -s ${MAN_DIR}/rmcvsdir-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/rmcvsdir.1.gz
ln -s ${MAN_DIR}/unitdiff-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/unitdiff.1.gz
ln -s ${MAN_DIR}/delp-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/delp.1.gz
ln -s ${MAN_DIR}/fpcmake-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpcmake.1.gz
ln -s ${MAN_DIR}/fpcsubst-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpcsubst.1.gz
ln -s ${MAN_DIR}/h2pas-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/h2pas.1.gz
ln -s ${MAN_DIR}/plex-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/plex.1.gz
ln -s ${MAN_DIR}/ppdep-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ppdep.1.gz
ln -s ${MAN_DIR}/ppudump-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ppudump.1.gz
ln -s ${MAN_DIR}/ppufiles-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ppufiles.1.gz
ln -s ${MAN_DIR}/ppumove-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ppumove.1.gz
ln -s ${MAN_DIR}/ptop-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/ptop.1.gz
ln -s ${MAN_DIR}/pyacc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/pyacc.1.gz
ln -s ${MAN_DIR}/rstconv-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/rstconv.1.gz
ln -s ${MAN_DIR}/fpdoc-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpdoc.1.gz
ln -s ${MAN_DIR}/fpclasschart-2.6.4.1.gz ${DESTDIR}/${MAN_DIR}/fpclasschart.1.gz
ln -s /usr/share/man/man5/fpcmake-2.6.4.5.gz ${DESTDIR}/usr/share/man/man5/fpcmake.5.gz
ln -s /usr/share/man/man5/ptop-2.6.4.cfg.5.gz ${DESTDIR}/usr/share/man/man5/ptop.cfg.5.gz
